package main

import (
	"box-service/service"
	"log"

	"github.com/gin-contrib/sessions"
	"github.com/gin-contrib/sessions/cookie"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	// swagger embed files
	_ "box-service/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Example Box Service
// @version 1
// @host localhost:8080
// @basepath /api/v1
// @license.name ISC
func main() {
	log.Println("Welcome To Box Service")
	log.SetFlags(log.LstdFlags | log.Lshortfile)
	launch()
}

func launch() {
	r := gin.Default()
	port := "8080"

	sessionStorage := cookie.NewStore([]byte("secret"))
	r.Use(sessions.Sessions("auth", sessionStorage))

	v1 := r.Group("api/v1")

	boxService := service.Service{}

	authService := service.AuthHandler{}

	v1.POST("/boxes", boxService.New)
	v1.POST("/boxes/big", boxService.NewBigBox)
	v1.GET("/boxes", boxService.List)
	v1.POST("/signin", authService.SignIn)

	swagConfig := &ginSwagger.Config{
		URL: "http://localhost:" + port + "/swagger/doc.json",
	}

	r.GET("/swagger/*any", ginSwagger.CustomWrapHandler(swagConfig, swaggerFiles.Handler))

	r.Run(":" + port)

}
